### ISSUE TITLE
3.0.0 version throw  `knex.client._formatQuery is not a function` when i start egg application.

### ISSUE THREAD

**Issue by LiuJiJiJi** [eggjs/egg-knex#31]
## knex.client._formatQuery is not a function
 
 ```bash
 2021-05-14 19:00:20,137 ERROR 81953 nodejs.TypeError: knex.client._formatQuery is not a function
    at Function.<anonymous> (/Users/colin/work/eggjs_demo/backend/node_modules/egg-knex/lib/knex.js:171:23)
    at Function.emit (events.js:315:20)
    at Client_MySQL.<anonymous> (/Users/colin/work/eggjs_demo/backend/node_modules/knex/lib/knex-builder/make-knex.js:300:10)
    at Client_MySQL.emit (events.js:315:20)
    at /Users/colin/work/eggjs_demo/backend/node_modules/knex/lib/execution/runner.js:154:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Runner.ensureConnection (/Users/colin/work/eggjs_demo/backend/node_modules/knex/lib/execution/runner.js:272:14)
    at async Runner.run (/Users/colin/work/eggjs_demo/backend/node_modules/knex/lib/execution/runner.js:30:19)
    at async isReady (/Users/colin/work/eggjs_demo/backend/node_modules/egg-knex/lib/knex.js:128:20)

pid: 81953
hostname: xxxxx

2021-05-14 19:00:20,137 ERROR 81953 [app_worker] start error, exiting with code:1
```

**Comment by sunfuze** [comment]
fix in 3.0.1
